server:  
  port: ${PORT:8888}
  
spring:
  application:
    name: config-server
  security:
    user:
      name: myusername
      password: mypassword

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://myusername:mypassword@localhost:8760/eureka/
 


 