spring:
   config:
      activate:
         on-profiles: node2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
server:  
  port: ${PORT:8762}