spring:
   config:
      activate:
         on-profiles: node2
eureka:
  instance:
    hostname: localhost
    metadataMap:
       zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:  
  port: ${PORT:8762}