spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: node2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:  
  port: ${PORT:8762}