spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: node1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:  
  port: ${PORT:8761}
  
  

