spring:
   config:
      activate:
         on-profiles: node1
eureka:
  instance:
    hostname: localhost
    metadataMap:
       zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:  
  port: ${PORT:8761}
  
  

