spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: peer1
      metadataMap:
         zone: zone1
eureka:
  instance:
    hostname: peer1
#    metadataMap:
#       zone: zone1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
server:  
  port: ${PORT:8761}