spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: peer2
      metadataMap:
         zone: zone2
eureka:
  instance:
    hostname: peer2
#    metadataMap:
#       zone: zone2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
server:  
  port: ${PORT:8762}