spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: node1
eureka:
  instance:
    metadataMap:
       zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:  
  port: ${PORT:8761}
  
  

