spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: node2
eureka:
  instance:
    hostname: node2
    metadataMap:
       zone: zone2
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/
server:  
  port: ${PORT:8762}