spring:
   application:
      name: discovery-service
   config:
      activate:
         on-profiles: node3
eureka:
  instance:
    metadataMap:
       zone: zone3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:  
  port: ${PORT:8763}