spring:
   application:
      name: gateway-service
   cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: book-service
          uri: http://localhost:8092
          predicates:
            - Path=/library/**
   security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/test/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/test
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: VvQXimbn43QmNLljL7f4EvWiBdXTLtRa
            authorization-grant-type: authorization_code
            scope: openid

management:
   endpoint: 
      health:
         show-details: always
   endpoints: 
      web:
         exposure:
            include: '*' 
            
logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE 
  
server:
   port: ${PORT:8090}


