spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
   
eureka: 
   client: 
      registerWithEureka: false 
      registryFetchIntervalSeconds: 1 
      shouldDisableDelta: true
   instance:
      leaseRenewalIntervalInSeconds: 1 
      leaseExpirationDurationInSeconds: 1
      

