server:
   port: ${PORT:8080}
   
spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
   
eureka: 
   client: 
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      registerWithEureka: false 
      registryFetchIntervalSeconds: 1 
      shouldDisableDelta: true
   instance:
      leaseRenewalIntervalInSeconds: 1 
      leaseExpirationDurationInSeconds: 1
      

