spring: 
   config:
      activate:
         on-profiles: zone1  
         
eureka:
  instance:
    metadataMap:
       zone: zone1
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      
server: 
   port: ${PORT:8181}
