spring: 
   config:
      activate:
         on-profiles: zone2  
         
eureka:
  instance:
    metadataMap:
       zone: zone2
  client:
    serviceUrl:
      defaultZone: http://zone2:8762/eureka/,http://zone1:8761/eureka/
      
server: 
   port: ${PORT:8182}