spring:
   application:
      name: client-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1 
    leaseExpirationDurationInSeconds: 1
#    preferIpAddress: true
  client:
    preferSameZoneEureka: true
    registryFetchIntervalSeconds: 1
    shouldDisableDelta: true