spring:
   application:
      name: books-service
   rabbitmq:
      host: localhost
      port: 5672
   cloud:
      function:
         definition: receiveBookInfo
      stream:
         bindings:
            receiveBookInfo-in-0:
               destination: booInfo-out
            receiveBookInfoGroup-in-0:
               destination: bookInfoGrouped-out
               group: bookInfoGroup
            receiveBookInfoPartitioned-in-0:
               destination: bookInfoPartitioned-out
               consumer:
                  partitioned: true
                  instance-index: 0

server:
   port: ${PORT:8081}