spring: 
   config:
      activate:
         on-profiles: zone1  
         
eureka:
  instance:
    hostname: localhost
    metadataMap:
       zone: zone1
  client:
    serviceUrl:
      defaultZone: http://myusername:mypassword@localhost:8760/eureka/
            
server: 
   port: ${PORT:8085}
 
