spring:
   application:
      name: discovery-service
   cloud:
      gateway:
         mvc:
            enabled: 'true'
         routes:
            - id: add_request_header_route
              uri: http://book-service:8082/library/getAuthor
              predicates:
                 - Method=GET
                 - Path=/api/{segment}
              filters:
                 - AddRequestHeader=X-Request-red, blue-{segment}   
                                       
server:
   port: ${PORT:8080}