spring:
   application:
      name: discovery-service
   cloud:
      gateway:
         mvc:
            enabled: 'true'
         routes:
            - id: after_route
              uri: https://example.org
              predicates:
                 - After=2017-01-20T17:42:47.789-07:00[America/Denver]   
            - id: add_request_header_route
              uri: https://example.org
              filters:
                 - AddRequestHeader=X-Request-red, blue   
                                       
server:
   port: ${PORT:8760}