server:  
  port: ${PORT:8081}
  
spring:
  mvc:
     pathmatch:
        matching-strategy: ant_path_matcher
  security:
     user:
        name: username
        password: pass 
   
management:
   endpoint: 
      health:
         show-details: always
   endpoints: 
      web:
         exposure:
            include: '*'

myproperty: value22222
      
