server:
   port: ${PORT:8080}
   ssl:
      key-store: classpath:keystore.p12
      key-store-password: mypassword

myproperty: value

eureka:
  instance:
    hostname: localhost
    securePortEnabled: true 
    nonSecurePortEnabled: false 
    statusPageUrl: https://${eureka.hostname}:${server.port}/info 
    healthCheckUrl: https://${eureka.hostname}:${server.port}/health
    homePageUrl: https://${eureka.hostname}:${server.port}/ 