spring: 
   config:
      activate:
         on-profiles: zone1  
         
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
            
server: 
   port: ${PORT:8181}
 
