spring:
   application:
      name: client-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1 
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    shouldDisableDelta: true