server:
  port: ${PORT:8888}


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        decrypt:
          enabled: false
  profiles:
    active: native

encrypt:
  keyStore:
    location: classpath:/config.p12
    password: mypass
    alias: config
    secret: mypass