spring:
   application:
      name: author-service
   rabbitmq:
      host: localhost
      port: 5672
   cloud:
      function:
         definition: receiveBookInfo
      stream:
         bindings:
            receiveBookInfo-in-0:
               destination: booInfo-out    
               
server:  
   port: ${PORT:8082}   