spring:
   application:
      name: gateway-service
   cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: author-service
          uri: http://localhost:8091
          predicates:
            - Path=/authors/**
        - id: book-service
          uri: http://localhost:8092
          predicates:
            - Path=/library/**
            
management:
   endpoint: 
      health:
         show-details: always
   endpoints: 
      web:
         exposure:
            include: '*' 
            
logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE 
  
server:
   port: ${PORT:8090}


