server:
   port: ${PORT:8080}
   
spring:
   application:
      name: client-service
      
eureka:
  client:
    serviceUrl:
       defaultZone: http://myusername:mypassword@localhost:8760/eureka/




 