server:
   port: ${PORT:8080}
   
spring:
   application:
      name: client-service
   cloud: 
      config: 
         discovery: 
            enabled: true 
            serviceId: config-server
         
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://myusername:mypassword@localhost:8760/eureka/
       

 




 