spring:
  application:
    name: book-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:h2:mem:mydb'
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8080/realms/test/protocol/openid-connect/certs'
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/test
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: VvQXimbn43QmNLljL7f4EvWiBdXTLtRa
            authorization-grant-type: authorization_code
            scope: TEST 
                                      
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://myusername:mypassword@localhost:8760/eureka/'
server:
  port: '${PORT:8092}'
