spring:
   application:
      name: booksmanagement-service
   rabbitmq:
      host: localhost
      port: 5672
   cloud:
      function:
         definition: uppercase;receive;send;source;sendBookInfo
      stream:
         bindings:
            uppercase-in-0:
               destination: test-out
            uppercase-out-0:
               destination: test-in
            sink-in-0:
               destination: test-in
            source-out-0:
               destination: test-out  
            sendBookInfo-out-0:
               destination: bookInfo-out
            sendBookInfoGrouped-out-0:
               destination: bookInfoGrouped-out
                         
server:  
   port: ${PORT:8080}   