spring:
   application:
      name: booksmanagement-service
   rabbitmq:
      host: localhost
      port: 5672
   cloud:
      function:
         definition: uppercase;receive;send;source;sendBookInfo
      stream:
         bindings:
            uppercase-in-0:
               destination: test-in
            uppercase-out-0:
               destination: test-out
            receive-in-0:
               destination: test-out
            send-out-0:
               destination: test-in
            source-out-0:
               destination: test-in  
            sendBookInfo-out-0:
               destination: booInfo-out
                         
server:  
   port: ${PORT:8080}   