spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    loadbalancer:
       configurations: zone-preference
   
eureka: 
   client: 
      registerWithEureka: false 
      preferSameZoneEureka: true
      registryFetchIntervalSeconds: 3 
      shouldDisableDelta: true
   instance:
      leaseRenewalIntervalInSeconds: 1 
      leaseExpirationDurationInSeconds: 2
      

