server:
  port: ${PORT:8081}
spring: 
   profiles: zone1
eureka: 
   client: 
      serviceUrl: 
         defaultZone: http://node1:8761/eureka/ 
         registerWithEureka: false 
         preferSameZoneEureka: true
   instance: 
      metadataMap: 
         zone: zone1

